### ISSUE TITLE
关于搭建多节点的疑问

### ISSUE THREAD

**Issue by KinderRiven** [thustorage/Sherman#1]
您好，想问一下，搭建多节点的服务话是不是需要把所有节点连接到一个memcached实例中？
比如：我要在10, 12, 14节点搭建一个分布式的sherman服务，我需要让他们都连接到相同ip地址的memcached实例？

**Comment by Transpeptidase** [comment]
是的，需要一个memcached，所有的节点通过它交换qp信息，建立RC连接

**Comment by prokey2001** [comment]
Sorry to bother you again. I run two nodes, the node IP addresses are 192.168.100.135 (primary node) and 192.168.100.64 respectively. The memcached.conf of the latter node is configured as follows：
![image](https://user-images.githubusercontent.com/93810132/190437075-3a26aede-a08c-47ec-a49c-339c99e6c717.png
Connection failure occurs when running：
![image](https://user-images.githubusercontent.com/93810132/190437274-ac49cd85-4033-46e5-85df-b0b051e456d9.png)

**Comment by Transpeptidase** [comment]
> Sorry to bother you again. I run two nodes, the node IP addresses are 192.168.100.135 (primary node) and 192.168.100.64 respectively. The memcached.conf of the latter node is configured as follows： ![image](https://user-images.githubusercontent.com/93810132/190437075-3a26aede-a08c-47ec-a49c-339c99e6c717.png Connection failure occurs when running： ![image](https://user-images.githubusercontent.com/93810132/190437274-ac49cd85-4033-46e5-85df-b0b051e456d9.png)

See readme: restart memcached before each run.
