### ISSUE TITLE
Segmentation fault！（core dumped） when run benchmark！

### ISSUE THREAD

**Issue by prokey2001** [thustorage/Sherman#10]
When I am running benchmark, it occurs an error, it is as follows
![image](https://user-images.githubusercontent.com/93810132/190422711-a89015f4-6038-482a-973c-3345ac1c2318.png)
I guess this error is caused by incorrect huagepage or memory settings

**Comment by Transpeptidase** [comment]
Have you executed  ./script/hugepage.sh?

**Comment by prokey2001** [comment]
Oh，I forgot it! After executed ./script/hugepages.sh,it is worked!
![image](https://user-images.githubusercontent.com/93810132/190431462-124ada74-5600-4e49-be94-78ce71d1501c.png)
Thank you!
