### ISSUE TITLE
Got completion with error

### ISSUE THREAD

**Issue by Dicridon** [thustorage/Sherman#11]
Hi, thanks for your open source repo of Sherman, we are happy that we can run Sherman on our cluster to learn more about this system.

## The issue
We encountered protection error and deadlock running multithread and multi-machine benchmarks.

## Instructions executed
We use the following instructions **on each machine** to run multithread and multi-machine benchmarks, which produce runtime errors. The Memcached server is on a third machine.
```
./hugepage.sh
./restartMemc.sh
./benchmark 2 100 4
```
We run the following instructions to run the single-thread and single-machine benchmark, which runs well
```
./hupages.sh
./restartMemc.sh
./bencharmk 1 100 1
```
The total number of huge pages in the `hugepage.sh` is modified to 4096 to reduce prepare time and huge page size is 2MiB.

## Error messages
We were able to run a single-thread benchmark on a single machine, but we encountered the following errors when running multithread and multi-machine tests. 
![image](https://user-images.githubusercontent.com/24477137/191242496-9d6eab9c-c465-4531-9166-f0062b85d20c.png)

## Machine configuration
As shown above, RDMA poll failed due to protection error, and deadlock was detected. We are not sure whether this is caused by the wrong hardware configuration or software bugs. The machine configuration is as follows:
![image](https://user-images.githubusercontent.com/24477137/191244083-7808f0d5-9d57-4f36-a74b-6562d0762f15.png)
The hardware configuration seems to meet the requirement of Sherman (OFED version and firmware version).

## Analysis
The protection error is caused by access to invalid memory regions, but we are not sure whether this is caused by software bugs or the wrong hardware setup. The deadlock error is also confusing because the benchmarks are read-only. Can you give us some tips to debug these errors?

**Comment by Transpeptidase** [comment]
Hi,  `./restartMemc.sh` only needs to be executed *once* before each run: execute it on machine 1, but not machine 2.
Besides, the memached consumes almost no system resources, so you can co-locate it with Sherman processes.

**Comment by Dicridon** [comment]
Thanks for your quick reply, we now can run Sherman successfully!

**Comment by Dicridon** [comment]
Sorry for reopening this issue, but when running multi-machine benchmarks, we have the following errors when the thread number exceeds 4: 
on machine 0
![image](https://user-images.githubusercontent.com/24477137/191262000-c73adf28-b78c-450a-a225-35fa21861cbf.png)
on machine 1
![image](https://user-images.githubusercontent.com/24477137/191262023-2d347fbd-fe09-478f-9581-9430032821ab.png)

And if we start the two servers at almost the same time, we have an assertion failure `Assertion page->hdr.sibling_ptr != GlobalAddress::Null() failed`

**Comment by Transpeptidase** [comment]
Can you provide a screenshot of the entire test?

**Comment by Dicridon** [comment]
Sorry for my late reply. 
![image](https://user-images.githubusercontent.com/24477137/191495412-19bf58f6-bac1-4d67-a74b-a795d9e0f0fc.png)

**Comment by Transpeptidase** [comment]
I cannot see the complete output of server 0 (right part of screenshot )

**Comment by Dicridon** [comment]
The missing part is below
![image](https://user-images.githubusercontent.com/24477137/191499442-656a20c5-b5d9-4538-bbb6-f992efecb35a.png)
and the `registering 8589934592 memory region` is some output added by us to see the execution process of Sherman (these outputs are too long and repetitive. I can capture them all)

**Comment by Transpeptidase** [comment]
Can you check if the error is triggerred when performing 
https://github.com/thustorage/Sherman/blob/76e208bbc7db06a07b35ee56fa1164e4c36e6601/src/Tree.cpp#L67
or 
https://github.com/thustorage/Sherman/blob/76e208bbc7db06a07b35ee56fa1164e4c36e6601/src/Tree.cpp#L71
?

**Comment by Dicridon** [comment]
https://github.com/thustorage/Sherman/blob/76e208bbc7db06a07b35ee56fa1164e4c36e6601/src/Tree.cpp#L74
The above line triggers the error

**Comment by Transpeptidase** [comment]
Is it OK when the number of threads is 2?
Can you print the information of related variables?

**Comment by Dicridon** [comment]
Unfortunately currently 2-thread benchmark fails too and error messages are the same (I wonder if maybe I should reboot the machines after each run?)
I have the following variables with `-O0` optimization: 

![image](https://user-images.githubusercontent.com/24477137/191506504-437b77fd-531d-44cc-9a0f-0f9039641c2d.png)
The `root_addr.val`'s hex value is `0x20000000001`. It doesn't look like a valid value.

**Comment by Transpeptidase** [comment]
How about a single thread in each machine? Please check RDMA network state via running `ibv_write_bw`.

**Comment by Dicridon** [comment]
Running single-thread benchmarks sometime is OK and occasionally produces the same error.

ibv_write_bw works fine and our own programs also work.

**Comment by Dicridon** [comment]
This issue is weird because we successfully ran the multithread benchmark on two machines once, but currently it doesn't work, Maybe it is due to some machine state issue?

**Comment by Transpeptidase** [comment]
Can you insert ``while(true) {}`` after 
https://github.com/thustorage/Sherman/blob/76e208bbc7db06a07b35ee56fa1164e4c36e6601/test/benchmark.cpp#L258
?
Let's check if these two servers can init the tree successfully

**Comment by Dicridon** [comment]
Sorry for my so late reply, I'm currently busy on another project. 
The two servers can init the tree successfully after adding the loop.

**Comment by Transpeptidase** [comment]
Hi, can you send your WeChat ID via `q-wang18@mails.tsinghua.edu.cn` ? we  can communicate more efficiently through WeChat

**Comment by Dicridon** [comment]
Thank you so much for your help and I've sent my ID to you.
