### ISSUE TITLE
Sherman Evaluation

### ISSUE THREAD

**Issue by prokey2001** [thustorage/Sherman#12]
Hello, in the evaluation section of sherman, the performance of in memory database read and write operations is tested. I wonder if sherman can be used as a resource disaggregated system to run the network traffic trace of real applications，e.g. Tensorflow, Phoenix

**Comment by Transpeptidase** [comment]
Hi, you can use intel PIN to collect load/store instructions for apps, then repaly them. Refer to paper "MIND: in-network memory management for disaggregated data centers".
