### ISSUE TITLE
YCSB benchmark

### ISSUE THREAD

**Issue by songzhaozhe** [thustorage/Sherman#13]
Hi,

Your paper mentioned that you evaluated with the YCSB benchmark, but benchmark.cpp seems to be custom generated data. Was it a typo in the paper or I misunderstood something?

Thanks!

**Comment by Transpeptidase** [comment]
Hi, we use `zipf.h` to generate YCSB key distribution like many other paeprs.

**Comment by songzhaozhe** [comment]
Got it, thanks for explaining.
