### ISSUE TITLE
Traffic type on Sherman cluster

### ISSUE THREAD

**Issue by prokey2001** [thustorage/Sherman#15]
Hello! After reading your paper, I have already know that there will be RDMA network traffic between computing nodes and memory nodes. But I'm not sure whether there will be RDMA network traffic between memory nodes and memory nodes, or between computing nodes and computing notes. Or I plan to capture packets on the switch. Is it feasible to identify the traffic type by analyzing the packet header? We are looking forward to your reply. Thank you very much!

**Comment by Transpeptidase** [comment]
Hi, there is no RDMA network traffic between MN/MN or CN/CN

**Comment by prokey2001** [comment]
Ok！Thank you for your reply！
