### ISSUE TITLE
why use CityHash64 to process key in benchmark.cpp?

### ISSUE THREAD

**Issue by fangneverdown** [thustorage/Sherman#16]
inline Key to_key(uint64_t k) {
  return (CityHash64((char *)&k, sizeof(k)) + 1) % kKeySpace;
}

After Hashing, it is impossible to do range search and will overlap the origin {key1,value} if key2 and key1 meet hash collision

**Comment by Transpeptidase** [comment]
Hi, the `to_key` func (instead of the zipf generator) produces the Key. If the zipf generator produces `p`, it only means the client will access the p-th frequent Key (e.g., to_key(p)).

**Comment by fangneverdown** [comment]
ok, thank you!
