### ISSUE TITLE
it seems to be no 16bit lock on NIC memory

### ISSUE THREAD

**Issue by fangneverdown** [thustorage/Sherman#17]
Hello! it says in sherman paper that  "we make the granularity of RDMA_CAS finer (16 bits rather than 64 bits), by applying an infrequently used RDMA verb called masked compare and swap [2], which allows us to select a portion of 64-bit for RDMA_CAS operations" . But I didn't find any use of  " masked compare and swap " in the project and instead the function "cas_dm" uses 64 bits' "compare" and "swap".
Could you please explain the reason？

**Comment by Transpeptidase** [comment]
Yes, in the open-source code, we use 64-bit cas, see reason in https://github.com/thustorage/Sherman/blob/a75a93bcf6804c37f7363426f53b46cb53c0f157/include/Common.h#L91

For more fine-grained locks, please call   ``void DSM::cas_dm_mask``

**Comment by fangneverdown** [comment]
Have you tested the cas_dm_mask? Can cas_dm_mask support one bit lock?

**Comment by Transpeptidase** [comment]
Yes, its support 1bit ops.

**Comment by fangneverdown** [comment]
Thank you!
