### ISSUE TITLE
Why range query marked with "need fix"?

### ISSUE THREAD

**Issue by fangneverdown** [thustorage/Sherman#18]
Hello！I wonder why range query is not completed. Does it have to support version consistency when doing the range query which may cost a long time? I would aslo like to know why you don't use sibling pointer when doing range query.

**Comment by Transpeptidase** [comment]
The current implementation is a simplified version with the assumption that all innernal nodes are cached in compute nodes: https://github.com/thustorage/Sherman/blob/a75a93bcf6804c37f7363426f53b46cb53c0f157/src/Tree.cpp#L472
It does cause the anomalies that some kv entries are miss in the results when inserting new keys (updating keys will not induce the anomalies). We will fix it when we have time.

**Comment by fangneverdown** [comment]
OK，thanks！
