### ISSUE TITLE
Allocate on-chip memory failed

### ISSUE THREAD

**Issue by UntaggedRui** [thustorage/Sherman#2]
When I am running the benchmark, it shows that I can not allocate on-chip memory. 
My enviroment is as follows. The nic is ConnectX-5 Ex and NIC Firmware version is 16.32.1010, which is higher than 16.26.4012. 
What can I do to fix the problem?
<img width="613" alt="image" src="https://user-images.githubusercontent.com/28807947/172844630-366f7b20-5cbe-4785-b3c6-7ae23d82385c.png">

**Comment by Transpeptidase** [comment]
Hi, the output contains "NIC Device Memory is 128KB", so the NIC supports  on-chip memory".  You should modify ``kLockChipMemSize`` to 128 * 1024. https://github.com/thustorage/Sherman/blob/3f8039a4e0a171edc9c1f718b62b19e0ed21f6a6/include/Common.h#L88.

Thank you for reporting this issue :)

**Comment by UntaggedRui** [comment]
Thanks. It run successfully.
