### ISSUE TITLE
Missing implementation of fine-grained write back

### ISSUE THREAD

**Issue by baotonglu** [thustorage/Sherman#20]
Hi, The paper states that only the modified entry is written back to the memory pool to avoid the write amplification. However, in the source code, it seems that the whole node is already written back to the pool. Which part of the implementation is about fine-grained write-back? Look forward to your reply.

**Comment by Transpeptidase** [comment]
hi，refer to https://github.com/thustorage/Sherman/blob/a0d541e03a7b404d263f4fb8872de2a0c6d97c40/src/Tree.cpp#L917-L919

**Comment by baotonglu** [comment]
Thanks, got it!
