### ISSUE TITLE
How to allocate chip memory on new RDMA driver

### ISSUE THREAD

**Issue by baotonglu** [thustorage/Sherman#21]
My RDMA driver is the newest instead of the one used in this project MLNX_OFED_LINUX-4.7-3.2.9.0. Although I resolve most interface incompatibility, I cannot figure out how to allocate memory on the chip. Below is the error reported, can you take a look at how to fix it?
![Screenshot 2023-07-23 at 11 29 07 PM](https://github.com/thustorage/Sherman/assets/18624358/290af040-65af-49a0-bd3d-e69a85a8515e)

**Comment by Transpeptidase** [comment]
Hi, you can try the following interfaces:
https://man7.org/linux/man-pages/man3/ibv_alloc_dm.3.html

**Comment by baotonglu** [comment]
Thanks for your prompt reply, I fixed them.
