### ISSUE TITLE
Can I carry out this exp with only Connectx-4 nics and a 56Gb/s switch?

### ISSUE THREAD

**Issue by SSK015** [thustorage/Sherman#22]
Can I carry out this exp with only Connectx-4 nics and a 56Gb/s switch? It seems that sherman requires Connectx-5 and above ones to leverage the on-chip memory.

**Comment by Transpeptidase** [comment]
Hi. you can refer to dLSM (https://www.cs.purdue.edu/homes/csjgwang/pubs/ICDE23_dLSM.pdf); it uses CX-4 and evaluate sherman (uses their forked version https://github.com/ruihong123/Sherman)

**Comment by SSK015** [comment]
Yeah, I have seen this paper. I am a little dubious as he says he use Connectx-3 nics(In multinode Part) to carry out the exp. However, a link from NVIDIA which is no longer valid says on-chip memory is only available for Connectx-4 and above.

**Comment by SSK015** [comment]
> Hi. you can refer to dLSM (https://www.cs.purdue.edu/homes/csjgwang/pubs/ICDE23_dLSM.pdf); it uses CX-4 and evaluate sherman (uses their forked version https://github.com/ruihong123/Sherman)

Thanks for your reply

**Comment by Transpeptidase** [comment]
> Yeah, I have seen this paper. I am a little dubious as he says he use Connectx-3 nics(In multinode Part) to carry out the exp. However, a link from NVIDIA which is no longer valid says on-chip memory is only available for Connectx-4 and above.

you can call 
https://github.com/thustorage/Sherman/blob/a0d541e03a7b404d263f4fb8872de2a0c6d97c40/src/rdma/Utility.cpp#L37
to check device memory support
