### ISSUE TITLE
Question regrading root node consistency

### ISSUE THREAD

**Issue by juyoungbang** [thustorage/Sherman#26]
Hi.
I've came up with a quick question and hope I can get some help.
It seems that there are consistency issues on the update of the root node.

When I use the original benchmark code given in the open source, there is no problem.
I think this is because node 0 bulk loads 1024000 keys solely and avoids the problematic situation 
which occurs in the early phase of tree creation where the root is updated frequently. 

However, when I run my own benchmark without bulk loading on 2 machines (64 thread/machine)
it is continuously caught on assertion statements such as line 986 of src/Tree.cpp.

Can you give me any advice on the problem I'm struggling on?

Thanks.

**Comment by Transpeptidase** [comment]
Yes, when the tree is too small, concurrent insertions are prone to errors.
You can try to use one server to insert some data (i.e.. 10240 keys) first, to form a tree structure; 
then, perform your bencmark

**Comment by juyoungbang** [comment]
Thanks for your quick and clear answer:)
