### ISSUE TITLE
Bug report for Tree::leaf_page_search

### ISSUE THREAD

**Issue by QIANSUIMINGMINGMING** [thustorage/Sherman#27]
The concurrency control with the left and right versions has a bug even when we ignore the cache line issue mentioned in the SIGMOD 23 paper.
If there is a K-V pair in the tree being updated concurrently (K-V1 update to K-V2), I suppose Tree::search would return either V1 or V2. However, this code may cause Tree::search to return nothing (not found) instead of V1 or V2. 
![image](https://github.com/thustorage/Sherman/assets/45732235/a9cf6a98-68f9-4aa1-8341-0c61d121f717)
Please correct me if I am wrong.

**Comment by QIANSUIMINGMINGMING** [comment]
SInce as long as r.f_version != r.r_version, result.val will be kValueNull and Tree::search will return false.
![image](https://github.com/thustorage/Sherman/assets/45732235/f4de17b7-ef95-4bb3-a7d8-c66ce952ec1e)

**Comment by Transpeptidase** [comment]
Can you provide the test code ?

**Comment by QIANSUIMINGMINGMING** [comment]
I read the code and noticed the potential problem before.
However, I ran a simple test today and found that there seems no problem in practice. The test code is below. I modified Tree::coro_worker.
![image](https://github.com/thustorage/Sherman/assets/45732235/1f38d945-4988-461e-b964-0df7a88fda0b)
