### ISSUE TITLE
Question about #define CONFIG_ENABLE_CRC

### ISSUE THREAD

**Issue by QIANSUIMINGMINGMING** [thustorage/Sherman#28]
Sorry for the bother, but I want to ask a question about the "+2Level Ver" presented in the paper. 
Since the two-level version may induce inconsistency in some concurrent cases, I want to run Sherman without this optimization.
I.e, the "+Hierarchical" version presented in the paper.
From the code of InternalPage and LeafPage, I assume you do it by defining CONFIG_ENABLE_CRC.
![image](https://github.com/thustorage/Sherman/assets/45732235/96d51605-0d9b-4a92-aa5a-5ec105cd587f)
However, it doesn't work, and the benchmark.cpp keeps show 
![image](https://github.com/thustorage/Sherman/assets/45732235/4709be20-c18a-4aea-ac16-2a2b8bd3e8bf)
Can you guide me on how to run the "+Hierarchical" version of Sherman?

**Comment by Transpeptidase** [comment]
You can use the code  using CRC in the paper [Scaling Up Memory Disaggregated Applications With Smart](https://madsys.cs.tsinghua.edu.cn/publications/ASPLOS24-ren.pdf)
see  https://github.com/madsys-dev/smart/blob/master/btree/btree.cpp

**Comment by QIANSUIMINGMINGMING** [comment]
Ok, thanks
