### ISSUE TITLE
Command combination of RDMA CAS and RDMA READ

### ISSUE THREAD

**Issue by hust-anhang** [thustorage/Sherman#29]
Hello, Qing

Can the first RDMA CAS in Sherman's write request be combined with the second RDMA READ? This question arises from the design described in Section 3.3 of paper [1].

[1]Design Guidelines for Correct, Efficient, and Scalable Synchronization using One-Sided RDMA

Thanks!

**Comment by Transpeptidase** [comment]
you can combine the cas and the read. But if the cas fails,  you will waste the IOPS of reads

**Comment by hust-anhang** [comment]
Ok, thank you for your prompt response.
