### ISSUE TITLE
Questions about recvPadding selection

### ISSUE THREAD

**Issue by maZymaZe** [thustorage/Sherman#30]
Hello, Qing  
    I can not understand why the sender sends the RawMessage with offset 0 in RawMessageConnection::sendRawMessage, while the receiver gets the RawMessage with the offset recvPadding(40) in  [AbstractMessageConnection::getMessage](https://github.com/thustorage/Sherman/blob/a0d541e03a7b404d263f4fb8872de2a0c6d97c40/src/AbstractMessageConnection.cpp#L59). That 40 is a magic number to me. Could you please tell me how does this rpc work with the offset 40?  
Thanks!

**Comment by Transpeptidase** [comment]
hi, in RDMA UD connection, the receive-side will contain 40B header.
Refer to https://docs.nvidia.com/networking/display/rdmaawareprogrammingv17/key+concepts

**Comment by maZymaZe** [comment]
Thank you for the helpful response!
