### ISSUE TITLE
About the Memcached and Cluster setup

### ISSUE THREAD

**Issue by baotonglu** [thustorage/Sherman#4]
您好, 

我有一些关于Memcached和集群搭建的问题。 

1. 我不太清楚Memcached在这个project的作用是什么。集群中的每个节点都要和Memcached通讯吗？为什么节点之间不直接相连？ 

2. Memcached是需要跑在一个单独的节点中吗？以及您能不能提供一下instruction/guide如何build/run Memcached。这部分在README中不是很清楚。

3. 关于这个命令````./benchmark kNodeCount kReadRatio kThreadCount````, kNodeCount, kReadRatio, kThreadCount各自的含义是什么？ 

Thanks!

**Comment by Transpeptidase** [comment]
Hi，

1. 这个memcached是用来节点之间交换QP元数据的（RDMA建立连接之前需要带外交换QP元数据），所以每个节点都要和Memcached通讯。这个是RDMA系统里比较常用的方法，memcached还可以做一些同步的事。
2. 由于memcached做的事情比较简单，可以随便运行在某个节点（不需要单独节点）。memcached的话之间用apt或者yum安装就行了，readme里讲了怎么启动它（restartMemc.sh，里面使用ssh执行远程命令，如果嫌输入密码麻烦，就设置一下免密ssh或者使用sshpass）。
3. kNodeCount就是集群里几台机器，kReadRatio就是get的比例（0-100）；kThreadCount就是每个机器运行的client thread个数

**Comment by baotonglu** [comment]
谢谢解答。
````../memcached.conf```` 中的IP和port应该就是指定在Memcached在哪个server上运行是吗？
这个port应该就是我平时ssh登录server的端口，不需要特殊的端口是吧？

**Comment by Transpeptidase** [comment]
port是memcached的端口，没被占用的都能用，不是ssh的22

**Comment by baotonglu** [comment]
Thanks!
