### ISSUE TITLE
Example problem to enable coroutine of Sherman

### ISSUE THREAD

**Issue by baotonglu** [thustorage/Sherman#7]
Hi,

From the operation interface of Sherman (e.g., insert, search), it seems that it already implemented the logic of coroutine. 

But it is unclear to me how to enable the coroutine execution of Sherman. For example, how to fill the parameter ````CoroContext ```` and ````coro_id````. Could you give me an example program of the coroutine execution of Sherman?

Thanks!

**Comment by Transpeptidase** [comment]
Hi, in `benchmark.cpp`, you can open the macro `USE_CORO` to enable coroutine, then each thread will bind `kCoroCnt` coroutine.
This will call `run_coroutine` method in `Tree.cpp`, which inits  `kCoroCnt` worker coroutine (which issues index ops, and coro_id is '0..kCoroCnt-1'. coro_id will be embeded in wr_id of RDMA work request) and a master coroutine (which polls cq to learn which worker to yeild).

**Comment by baotonglu** [comment]
: ) Thank you very much!
