### ISSUE TITLE
"Caching first 2 levels" missing?

### ISSUE THREAD

**Issue by songzhaozhe** [thustorage/Sherman#8]
I don't see the caching of "the highest two level of nodes (including root)" mentioned in paper from this code. There is only a skiplist `index_cache` for the level above leaves.

Is it removed intentionally? I was trying to find this code because caching the first 2 levels does not seem compatible with fence key checks in my opinion - imagine that a b-link style split have split the children but have not propagated to upper levels.

BTW, regardless, I like the paper!

**Comment by Transpeptidase** [comment]
yes, we found that caching first 2 levels may induce inconsistency and has no obvious performance improvement, so in the current version of the code, we only cache the address of the root page (``g_root_ptr``) and when a client thread installs a new root page, it broadcasts the new ``g_root_ptr`` via function ``Tree::broadcast_new_root``

**Comment by songzhaozhe** [comment]
Got it, thanks for the quick reply!
