### ISSUE TITLE
How to launch a memory thread in memory node? I mean which executable file should I use? benchmark?

### ISSUE THREAD

**Issue by dxlog0** [thustorage/Sherman#9]

**Comment by dxlog0** [comment]
May I misunderstand " Due to the limited size of our cluster, we emulate each server as one MS and one CS. Each MS owns 64GB DRAM and 2 CPU cores, and each CS owns 1GB DRAM and 22 CPU cores."

So,shoud I just run bencnmark on each node, and these nodes are memory nodes too? emm, then how to limits the CPU cores in MS and the DRAM size in CS?

**Comment by Transpeptidase** [comment]
Yes, when you run benchmark, each process will launch a memory thread to serve memory chunk allocation:
https://github.com/thustorage/Sherman/blob/76e208bbc7db06a07b35ee56fa1164e4c36e6601/src/Directory.cpp#L25

We limit the CPU cores by creating the fixed number of threads, limit the MS memory by setting the ``conf.dsmSize`` in ``DSM class``, and limit the CS memory by setting the ``cache_size`` in ``IndexCache class``:

https://github.com/thustorage/Sherman/blob/76e208bbc7db06a07b35ee56fa1164e4c36e6601/src/DSM.cpp#L34

https://github.com/thustorage/Sherman/blob/76e208bbc7db06a07b35ee56fa1164e4c36e6601/include/IndexCache.h#L55
